namespace HCM.API.Models
{
    public class MstEmployeeVM
    {
        public int Id { get; set; }
        public string EmpId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string ManagerName { get; set; }
        public string DesignationName { get; set; }
        public string PositionName { get; set; }
        public string DepartmentName { get; set; }
        public string LocationName { get; set; }
        public string BranchName { get; set; }
        public string OfficePhone { get; set; }
        public string OfficeExtension { get; set; }
        public string OfficeMobile { get; set; }
        public string HomePhone { get; set; }
        public string OfficeEmail { get; set; }
        public string Wastreet { get; set; }
        public string WastreetNo { get; set; }
        public string Wablock { get; set; }
        public string WazipCode { get; set; }
        public string Wacity { get; set; }
        public string Wastate { get; set; }
        public string Wacountry { get; set; }
        public string Hastreet { get; set; }
        public string HastreetNo { get; set; }
        public string Hablock { get; set; }
        public string HazipCode { get; set; }
        public string Hacity { get; set; }
        public string Hastate { get; set; }
        public string Hacountry { get; set; }
        public string PriPersonName { get; set; }
        public string PriRelationShip { get; set; }
        public string PriContactNoLandLine { get; set; }
        public string PriContactNoMobile { get; set; }
        public string PriAddress { get; set; }
        public string PriCity { get; set; }
        public string PriState { get; set; }
        public string PriCountry { get; set; }
        public string SecPersonName { get; set; }
        public string SecRelationShip { get; set; }
        public string SecContactNoLandline { get; set; }
        public string SecContactNoMobile { get; set; }
        public string SecAddress { get; set; }
        public string SecCity { get; set; }
        public string SecState { get; set; }
        public string SecCountry { get; set; }
        public string FatherName { get; set; }
        public DateTime? Dob { get; set; }
        public string GenderId { get; set; }
        public string BloodGroupId { get; set; }
        public string MotherName { get; set; }
        public string MartialStatusId { get; set; }
        public string ReligionId { get; set; }
        public string SocialSecurityNo { get; set; }
        public string EmpUnion { get; set; }
        public string UnionMembershipNo { get; set; }
        public string Nationality { get; set; }
        public string Idno { get; set; }
        public DateTime? IddateofIssue { get; set; }
        public string IdplaceofIssue { get; set; }
        public string IdissuedBy { get; set; }
        public DateTime? IdexpiryDate { get; set; }
        public string PassportNo { get; set; }
        public DateTime? PassportDateofIssue { get; set; }
        public DateTime? PassportExpiryDate { get; set; }
        public string IncomeTaxNo { get; set; }
        public decimal? BasicSalary { get; set; }
        public string HolidayCalendar { get; set; }
        public string SalaryCurrency { get; set; }
        public string PersonalEmail { get; set; }
        public string PersonalContactNo { get; set; }
        public string EmployeeContractType { get; set; }
        public string PayrollName { get; set; }
        public DateTime? JoiningDate { get; set; }
        public DateTime? ResignDate { get; set; }
        public bool? FlgActive { get; set; }
        public string GratuityName { get; set; }
        public string PaymentMode { get; set; }
        public DateTime? EffectiveDate { get; set; }
        public decimal? PercentagePaid { get; set; }
        public string AccountTitle { get; set; }
        public string BankName { get; set; }
        public string AccountNo { get; set; }
        public string AccountType { get; set; }
        public DateTime? TerminationDate { get; set; }
        public bool? FlgOtapplicable { get; set; }
        public bool? FlgSuperVisor { get; set; }
        public bool? FlgDailyWager { get; set; }
        public bool? FlgTax { get; set; }
        public bool? FlgEmail { get; set; }
        public decimal? GrossSalary { get; set; }
        public bool? FlgSandwich { get; set; }
        public string BonusCode { get; set; }
        public bool? FlgMedicalExempt { get; set; }

    }
}
